apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quest-approval-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Pratiks-96/Quest-Approval-Game-Saga-Workflow-.git'
    targetRevision: main
    path: helm/quest-game
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true        # Automatically delete resources not in git
      selfHeal: true     # Automatically fix drift
    syncOptions:
      - CreateNamespace=true
